### ISSUE TITLE
The result of crc16(str) needs to be processed again to make sure it's a  4-character Alphanumeric value

### ISSUE THREAD

**Issue by MINISOCKS** [ThunderQuoteTeam/PaynowQR#1]
Sometimes I got one or two 1-byte hexadecimal values using this:  this.crc16(str + '6304')
result like: 'E10'  or '9B', which should be '0E10' and '009B'
It caused the generated paynow string to be invalid.

The source code is as below:
![image](https://user-images.githubusercontent.com/22314673/89509871-6c7eb980-d802-11ea-9bdf-8d6420dfb546.png)

It can be fixed like this:
![image](https://user-images.githubusercontent.com/22314673/89509958-8b7d4b80-d802-11ea-96fc-96a1a8be5717.png)

**Comment by thenewcoda** [comment]
Hi MINISOCKS,

Firstly, thank you for using the PaynowQR library!

Secondly, thank you for your valuable report. We have updated the library with the fix, and also the NPM package. Feel free to test and contact us again should the problem persists or if you have any feedback regarding this, or any other issue.

Sincerely,
ThunderQuote Team.
