### ISSUE TITLE
TypeError: PaynowQR is not a constructor

### ISSUE THREAD

**Issue by autogeosystems** [ThunderQuoteTeam/PaynowQR#2]
Hi ThunderQuoteTeam, I saw your thread on https://github.com/jtaych/PayNow-QR-Javascript/issues/1 regarding that lib not being able to handle UENs, so I came over here to try your solution.

I am tried to run your example a few ways.

```
      const PaynowQR = require("paynowqr");

      let qrcode = new PaynowQR({
        uen: "201403121W", //Required: UEN of company
        amount: 500, //Specify amount of money to pay.
        editable: true, //Whether or not to allow editing of payment amount. Defaults to false if amount is specified
        expiry: "20201231", //Set an expiry date for the Paynow QR code (YYYYMMDD). If omitted, defaults to 5 years from current time.
        refNumber: "TQINV-10001", //Reference number for Paynow Transaction. Useful if you need to track payments for recouncilation.
        company: "ACME Pte Ltd.", //Company name to embed in the QR code. Optional.
      });
```

When I installed via `npm i paynowqr`

I'm get an error on `let qrcode = new PaynowQR({ ...`

`TypeError: PaynowQR is not a constructor`

When I tried using the script tag instead it works.

`<script src="https://unpkg.com/paynowqr@latest/dist/paynowqr.min.js"></script>`

Any idea why that might happen?

**Comment by limexd-em** [comment]
I've tried to replicate your issue but wasn't able to do so.

`TypeError: PaynowQR is not a constructor` means the variable `PaynowQR` isn't a valid function/class constructor. 

Have you tried installing the npm module in an empty project?
What version of nodejs are you using? 

Also, could you console.log the `PaynowQR` variable and let me know the output?

**Comment by autogeosystems** [comment]
Thanks for your message Emil.

It's been a while since I've looked at this so let me get back to you later
this week after I've had a chance to refresh and try what you suggested.

Cheers,
Nick

**Comment by limexd-em** [comment]
I'm going to close this issue, since there hasn't been an update for a while, and I'm not able to replicate. 

Feel free to reopen it if you can provide me with more information.

**Comment by huaizhic** [comment]
Ran into this issue too, turns out I only included the code from example.js but not paynowqr.js from the src folder. Including both files helped me to resolve this issue.
