### ISSUE TITLE
QR to support above SGD1000 (not editable)

### ISSUE THREAD

**Issue by VisheshJaiswal** [ThunderQuoteTeam/PaynowQR#3]
**Is your feature request related to a problem? Please describe.**
Currently the QR automatically fill an amount only if its less than SGD1000

**Describe the solution you'd like**
It will be greater if the QR can also be generated for SGD1000 and above

**Describe alternatives you've considered**
I just set the _editable_ parameter to true so the user can manually enter.

**Comment by limexd-em** [comment]
I've checked, am able to enter an amount above 1000 without issue and the QR code generates the correct amount, even when not editable. Tested using DBS PayLah App.

Could I have a code sample you used to create the QR code? And the Bank app used to scan the code?
![IMG_3474](https://user-images.githubusercontent.com/25244900/129808325-bc4da483-18db-4c60-bc57-6c327db4d2c5.PNG)
