### ISSUE TITLE
Does paynow QR work if recipient uses personal bank account?

### ISSUE THREAD

**Issue by simkimsia** [ThunderQuoteTeam/PaynowQR#4]

**Comment by limexd-em** [comment]
Currently code only allows for uen numbers (corporate). 

For personal numbers, you can look at adjusting the code here (untested)
https://github.com/ThunderQuoteTeam/PaynowQR/blob/21c4b0059c758f457fba99d21034f1de317ee8a4/src/paynowqr.js#L99

I might consider adjusting the code in future to allow personal phone number/ICs

You can also take a look at this library - it works for mobile numbers but not UENs
https://github.com/jtaych/PayNow-QR-Javascript
