### ISSUE TITLE
PaynowQr code expiry

### ISSUE THREAD

**Issue by edmundsiah81** [ThunderQuoteTeam/PaynowQR#5]
can it be set with time?

Meaning to let it expiry within 10 minutes?

**Comment by thenewcoda** [comment]
Hi, you do have the expiry option actually.

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Test

**Comment by thenewcoda** [comment]
Hi, the SG PayNow QR Code spec only allows the expiry to be on a day basis (date). If you need to do a time-based expiry, you might need to create it yourself as a web application.
